### ISSUE TITLE
better_errors does not report the actual error and gives wrong line.

### ISSUE THREAD

**Issue by envygeeks** [BetterErrors/better_errors#222]
Actual error in terminal:

```
SyntaxError - 
app/controllers/namespace/my_controller.rb:15: syntax error, unexpected tSTRING_BEG, expecting '}'
    "update" => [
     ^
app/controllers/namespace/my_controller.rb:15: syntax error, unexpected =>, expecting keyword_end
    "update" => [
               ^
app/controllers/namespace/my_controller.rb:18: syntax error, unexpected '}', expecting keyword_end:
  activesupport (4.0.2) lib/active_support/dependencies.rb:424:in `'
  activesupport (4.0.2) lib/active_support/dependencies.rb:424:in `block in load_file'
```

However, the error from better errors jumps right to activesupport instead of showing the proper file which is at the head of the error, it also shows activesupports code, instead of the controller that caused the error.  There is no application trace even available for the error either which is fine, but if it's going to force it to full stack then shouldn't it show the full error?

This is on Rails 4.0.2 btw.

**Comment by envygeeks** [comment]
If this is about me. It is pretty obvious you didn’t or are unable to even do the most basic due diligence before making such an ignorant comment.
