### ISSUE TITLE
FiberError on Pry

### ISSUE THREAD

**Issue by chibicode** [BetterErrors/better_errors#286]
I'm using `pry`, and getting this error when you type something into the REPL:

```
FiberError (dead fiber called):
01:11:50 web.1    |   better_errors (2.0.0) lib/better_errors/repl/pry.rb:48:in `resume'
01:11:50 web.1    |   better_errors (2.0.0) lib/better_errors/repl/pry.rb:48:in `block in send_input'
01:11:50 web.1    |   better_errors (2.0.0) lib/better_errors/repl/pry.rb:70:in `local'
01:11:50 web.1    |   better_errors (2.0.0) lib/better_errors/repl/pry.rb:47:in `send_input'
01:11:50 web.1    |   better_errors (2.0.0) lib/better_errors/error_page.rb:49:in `do_eval'
01:11:50 web.1    |   better_errors (2.0.0) lib/better_errors/middleware.rb:132:in `internal_call'
01:11:50 web.1    |   better_errors (2.0.0) lib/better_errors/middleware.rb:75:in `better_errors_call'
01:11:50 web.1    |   better_errors (2.0.0) lib/better_errors/middleware.rb:57:in `call'
01:11:50 web.1    |   actionpack (4.0.11) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
01:11:50 web.1    |   actionpack (4.0.11) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
01:11:50 web.1    |   railties (4.0.11) lib/rails/rack/logger.rb:38:in `call_app'
01:11:50 web.1    |   railties (4.0.11) lib/rails/rack/logger.rb:22:in `call'
01:11:50 web.1    |   quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets'
01:11:50 web.1    |   actionpack (4.0.11) lib/action_dispatch/middleware/request_id.rb:21:in `call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/runtime.rb:17:in `call'
01:11:50 web.1    |   activesupport (4.0.11) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/lock.rb:17:in `call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
01:11:50 web.1    |   /Users/shu/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/raven-ruby-d236bc9ee24d/lib/raven/rack.rb:59:in `call'
01:11:50 web.1    |   rack-mini-profiler (0.9.1) lib/mini_profiler/profiler.rb:300:in `call'
01:11:50 web.1    |   railties (4.0.11) lib/rails/engine.rb:511:in `call'
01:11:50 web.1    |   railties (4.0.11) lib/rails/application.rb:97:in `call'
01:11:50 web.1    |   railties (4.0.11) lib/rails/railtie/configurable.rb:30:in `method_missing'
01:11:50 web.1    |   rack (1.5.2) lib/rack/static.rb:119:in `call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/static.rb:119:in `call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/static.rb:119:in `call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/deflater.rb:25:in `call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/lint.rb:49:in `_call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/lint.rb:37:in `call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/showexceptions.rb:24:in `call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/commonlogger.rb:33:in `call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/chunked.rb:43:in `call'
01:11:50 web.1    |   rack (1.5.2) lib/rack/content_length.rb:14:in `call'
01:11:50 web.1    |   unicorn (4.6.3) lib/unicorn/http_server.rb:552:in `process_client'
01:11:50 web.1    |   unicorn (4.6.3) lib/unicorn/http_server.rb:632:in `worker_loop'
01:11:50 web.1    |   newrelic_rpm (3.7.3.199) lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `call'
01:11:50 web.1    |   newrelic_rpm (3.7.3.199) lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `block (4 levels) in <top (required)>'
01:11:50 web.1    |   unicorn (4.6.3) lib/unicorn/http_server.rb:500:in `spawn_missing_workers'
01:11:50 web.1    |   unicorn (4.6.3) lib/unicorn/http_server.rb:142:in `start'
01:11:50 web.1    |   unicorn (4.6.3) bin/unicorn:126:in `<top (required)>'
01:11:50 web.1    |   /Users/shu/.rbenv/versions/2.1.4/bin/unicorn:23:in `load'
01:11:50 web.1    |   /Users/shu/.rbenv/versions/2.1.4/bin/unicorn:23:in `<main>'
```

Gem versions:
- `better_errors`: 2.0.0
- `pry`: 0.10.1
- `binding_of_caller`: 0.7.2
- `rails`: 4.0.11

Other notes:
- Not using any other `pry-*` gems
- My `.pryrc` is empty
- Everything works fine if I turn of `use_pry!`

Any other information I should provide?

**Comment by bascht** [comment]
Can confirm:

```
Started POST "/__better_errors/f1ce759a39589f43/eval" for 192.168.33.1 at 2015-01-06 20:41:51 +0000

FiberError (dead fiber called):
  better_errors (2.1.0) lib/better_errors/repl/pry.rb:48:in `resume'
  better_errors (2.1.0) lib/better_errors/repl/pry.rb:48:in `block in send_input'
  better_errors (2.1.0) lib/better_errors/repl/pry.rb:70:in `local'
  better_errors (2.1.0) lib/better_errors/repl/pry.rb:47:in `send_input'
  better_errors (2.1.0) lib/better_errors/error_page.rb:49:in `do_eval'
  better_errors (2.1.0) lib/better_errors/middleware.rb:132:in `internal_call'
  better_errors (2.1.0) lib/better_errors/middleware.rb:75:in `better_errors_call'
  better_errors (2.1.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
  ahoy_matey (1.1.0) lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
  quiet_assets (1.0.3) lib/quiet_assets.rb:23:in `call_with_quiet_assets'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.8) lib/rails/engine.rb:514:in `call'
  railties (4.1.8) lib/rails/application.rb:144:in `call'
  railties (4.1.8) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.8) lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```
* Ruby 2.1.2p95
* better_errors (2.1.0)
* binding_of_caller (0.7.2)
* pry (0.10.0)
* pry-rails (0.3.2)
* rails (4.1.8)
