### ISSUE TITLE
Doesn't work with Rails 4.2 + Pry 0.10.x combo

### ISSUE THREAD

**Issue by miharekar** [BetterErrors/better_errors#293]
I just upgraded my app to rails 4.2 and REPL isn't working. I get the page and everything and I can type in:
![screen shot 2015-01-05 at 16 32 39](https://cloud.githubusercontent.com/assets/986645/5615130/73e89d7e-94f8-11e4-85b7-639030ac6e0e.png)
but after I press enter nothing happens. Downgrading to pry 0.9 and/or going back to rails 4.1 fixes the issue.

In the server log I get the following:

```

Started POST "/__better_errors/96e9523cc84abd06/variables" for 127.0.0.1 at 2015-01-05 16:34:20 +0100


Started POST "/__better_errors/96e9523cc84abd06/eval" for 127.0.0.1 at 2015-01-05 16:34:22 +0100

NoMethodError (private method `print' called for #<BetterErrors::REPL::Pry::Output:0x007f869b61f5c0 @buffer="">):
  pry (0.10.1) lib/pry/output.rb:25:in `block in print'
  pry (0.10.1) lib/pry/output.rb:24:in `each'
  pry (0.10.1) lib/pry/output.rb:24:in `print'
  pry (0.10.1) lib/pry/output.rb:16:in `block in puts'
  pry (0.10.1) lib/pry/output.rb:12:in `each'
  pry (0.10.1) lib/pry/output.rb:12:in `puts'
  pry (0.10.1) lib/pry/pry_instance.rb:381:in `rescue in rescue in show_result'
  pry (0.10.1) lib/pry/pry_instance.rb:375:in `rescue in show_result'
  pry (0.10.1) lib/pry/pry_instance.rb:386:in `show_result'
  pry (0.10.1) lib/pry/pry_instance.rb:336:in `block in handle_line'
  pry (0.10.1) lib/pry/pry_class.rb:369:in `critical_section'
  pry (0.10.1) lib/pry/pry_instance.rb:335:in `handle_line'
  pry (0.10.1) lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
  pry (0.10.1) lib/pry/pry_instance.rb:242:in `catch'
  pry (0.10.1) lib/pry/pry_instance.rb:242:in `block in eval'
  pry (0.10.1) lib/pry/pry_instance.rb:241:in `catch'
  pry (0.10.1) lib/pry/pry_instance.rb:241:in `eval'
  pry (0.10.1) lib/pry/repl.rb:77:in `block in repl'
  pry (0.10.1) lib/pry/repl.rb:67:in `loop'
  pry (0.10.1) lib/pry/repl.rb:67:in `repl'
  pry (0.10.1) lib/pry/repl.rb:38:in `block in start'
  pry (0.10.1) lib/pry/input_lock.rb:61:in `call'
  pry (0.10.1) lib/pry/input_lock.rb:61:in `__with_ownership'
  pry (0.10.1) lib/pry/input_lock.rb:79:in `with_ownership'
  pry (0.10.1) lib/pry/repl.rb:38:in `start'
  pry (0.10.1) lib/pry/pry_instance.rb:348:in `repl'
  better_errors (2.1.0) lib/better_errors/repl/pry.rb:37:in `block in initialize'


  Rendered /Users/mrfoto/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_source.erb (1.8ms)
  Rendered /Users/mrfoto/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.2ms)
  Rendered /Users/mrfoto/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /Users/mrfoto/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (39.7ms)
```

**Comment by sirwolfgang** [comment]
I seem to be running into this issue aswell. Removing Pry doesnt seem to help.

**Comment by mrfoto** [comment]
I think the problem is that in `Pry::REPL` the `output` is not set to `BetterErrors::REPL::Pry::Output` but I'm not sure. I tried aliasing `print` with `puts` but there are too many newlines and I don't know how to approach that. This issue  is really simple to reproduce - just update pry in gemfile and run the tests.

**Comment by aeberlin** [comment]
@mrfoto - Try this:

```
def print(*args)
  @buffer << args.join(' ')
end
```

**Comment by aeberlin** [comment]
Also, at `lib/better_errors/error_page.rb:40`, this will enable `last_exception` support:

```
    def do_eval(opts)
      index = opts["index"].to_i
      code = opts["source"]

      unless binding = backtrace_frames[index].frame_binding
        return { error: "REPL unavailable in this stack frame" }
      end

      repl = (@repls[index] ||= REPL.provider.new(binding))

      if repl.is_a?(REPL::Pry)
        pry = repl.instance_variable_get(:@pry)
        pry.instance_variable_set(:@last_exception, ::Pry::LastException.new(@exception.exception))
      end

      result, prompt, prefilled_input = (repl).send_input(code)

      { result: result,
        prompt: prompt,
        prefilled_input: prefilled_input,
        highlighted_input: CodeRay.scan(code, :ruby).div(wrap: nil) }
    end
```

It can be cleaned up, but it works!

**Comment by tmaier** [comment]
I ran into the same issue when I just activated pry support with `BetterErrors.use_pry!`
