### ISSUE TITLE
Latest Rack v2.2.0 is breaking this gem

### ISSUE THREAD

**Issue by kapso** [BetterErrors/better_errors#446]
```
NoMethodError (undefined method `reject' for nil:NilClass):
  
rack (2.2.0) lib/rack/request.rb:623:in `reject_trusted_ip_addresses'
rack (2.2.0) lib/rack/request.rb:363:in `ip'
better_errors (2.5.1) lib/better_errors/middleware.rb:67:in `allow_ip?'
better_errors (2.5.1) lib/better_errors/middleware.rb:56:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
```

```
rack (2.2.0)
gem 'better_errors', '2.5.1'
gem 'rails', '6.0.2.1'

ruby '2.7.0'
```

**Comment by kapso** [comment]
Looks like `rack (2.2.1)` has fixed the issue.
